# Generated by Django 2.2 on 2021-06-15 17:32

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('diseases', django_mysql.models.ListTextField(models.CharField(max_length=15, unique=True), default='hello', size=100)),
                ('treatments', django_mysql.models.ListTextField(models.CharField(max_length=15, unique=True), default='Hello', size=100)),
                ('noOfDoctors', models.IntegerField()),
                ('noOfBeds', models.IntegerField()),
                ('link', models.CharField(max_length=50, unique=True)),
                ('pincode', models.CharField(default='000000', max_length=6)),
                ('latitude', models.CharField(default='0.0', max_length=10)),
                ('longitude', models.CharField(default='0.0', max_length=10)),
            ],
        ),
    ]
