# Generated by Django 2.2 on 2021-06-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Image',
            field=models.CharField(default='image', max_length=100, unique=True),
        ),
    ]
