# Generated by Django 2.2 on 2021-06-16 06:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Restapi', '0002_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Image',
            field=models.CharField(default='image', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='diseases',
            field=django_mysql.models.ListTextField(models.CharField(max_length=15, unique=True), default='hello', size=150),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='link',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='treatments',
            field=django_mysql.models.ListTextField(models.CharField(max_length=15, unique=True), default='Hello', size=150),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(max_length=150),
        ),
    ]
